export const REGISTER_LOADING = 'REGISTER_LOADING'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_ERROR = 'REGISTER_ERROR'

export const LOGIN_LOADING = 'LOGIN_LOADING'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const CONTACTS_LOADING = 'CONTACTS_LOADING'
export const CONTACTS_LOADING_SUCCESS = 'CONTACTS_LOADING_SUCCESS'
export const CONTACTS_LOADING_ERROR = 'CONTACTS_LOADING_ERROR'

export const USER_LOGOUT = 'USER_LOGOUT'

export const CREATE_CONTACT_LOADING = 'CREATE_CONTACT_LOADING'
export const CREATE_CONTACT_SUCCESS = 'CREATE_CONTACT_SUCCESS'
export const CREATE_CONTACT_ERROR = 'CREATE_CONTACT_ERROR'
export const CLEAR_ADD_CONTACT = 'CLEAR_ADD_CONTACT'
